export const contactStyles = {
  section: {
    py: { xs: 5, md: 6 },
    px: { xs: 3, md: 3 },
    maxWidth: '1000px',
    mx: 'auto',
    backgroundColor: 'background.default',
  },
  inner: {},
  title: {
    fontWeight: 700,
    mb: 1,
  },
  description: {
    mb: 3,
    maxWidth: '640px',
    color: 'text.secondary',
    fontSize: '0.9rem',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: '1fr 1.4fr' },
    gap: 2.5,
    alignItems: 'start',
  },
  paper: {
    p: 3,
    height: '100%',
    backgroundColor: 'background.paper',
    border: '1px solid',
    borderColor: 'divider',
    borderRadius: 1.5,
    boxShadow: 'none',
  },
  paperTitle: {
    mb: 2,
    fontWeight: 700,
    fontSize: '1rem',
  },
  socialButton: {
    justifyContent: 'flex-start',
    py: 1,
    textTransform: 'none',
    fontSize: '0.85rem',
    color: 'text.primary',
    borderColor: 'divider',
    borderRadius: 1,
    '&:hover': {
      borderColor: 'text.primary',
      backgroundColor: 'transparent',
    },
  },
  submitButton: {
    py: 1,
    fontWeight: 700,
    fontSize: '0.85rem',
    backgroundColor: 'primary.main',
    color: 'primary.contrastText',
    boxShadow: 'none',
    '&:hover': { backgroundColor: '#000', boxShadow: 'none' },
  },
};
