export const heroStyles = {
  container: {
    pt: { xs: 11, md: 13 },
    pb: { xs: 5, md: 7 },
    px: { xs: 3, md: 3 },
    maxWidth: '1000px',
    mx: 'auto',
    backgroundColor: 'background.default',
  },
  grid: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    gap: { xs: 4, md: 5 },
    alignItems: { xs: 'flex-start', md: 'center' },
  },
  left: {
    flex: 1,
    minWidth: 0,
  },
  role: {
    fontSize: { xs: '1.35rem', md: '1.6rem' },
    fontWeight: 700,
    mb: 2,
  },
  skillsList: {
    listStyle: 'none',
    p: 0,
    m: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 0.9,
  },
  skillItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 1.1,
    fontSize: '0.95rem',
    lineHeight: 1.4,
    color: 'text.primary',
    '& svg': {
      fontSize: '1.2rem',
      flexShrink: 0,
    },
  },
  contact: {
    flex: 1,
    minWidth: 0,
  },
  contactItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 1,
    mb: 1.1,
    fontSize: '0.9rem',
    color: 'text.primary',
    '& svg': { fontSize: '1.1rem', color: 'text.secondary' },
  },
  contactLink: {
    color: 'text.primary',
    textDecoration: 'underline',
    textUnderlineOffset: '3px',
    '&:hover': { color: 'text.secondary' },
  },
  photoWrap: {
    display: 'flex',
    justifyContent: { xs: 'flex-start', md: 'flex-end' },
    flexShrink: 0,
  },
  photo: {
    width: { xs: 130, md: 200 },
    height: { xs: 130, md: 200 },
    borderRadius: '50%',
    border: '1px solid',
    borderColor: 'divider',
    fontSize: '2.5rem',
    fontWeight: 700,
    backgroundColor: 'primary.main',
    color: 'primary.contrastText',
  },
};
