export const projectsStyles = {
  section: {
    py: { xs: 5, md: 6 },
    px: { xs: 3, md: 3 },
    maxWidth: '1000px',
    mx: 'auto',
    backgroundColor: 'background.default',
  },
  inner: {},
  heading: {
    fontWeight: 700,
    mb: 3,
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, 1fr)' },
    gap: 2.5,
  },
  project: {
    display: 'flex',
    flexDirection: 'column',
    p: 2.5,
    height: '100%',
    backgroundColor: 'background.paper',
    border: '1px solid',
    borderColor: 'divider',
    borderRadius: 1.5,
    boxShadow: 'none',
    transition: 'transform 0.2s ease, border-color 0.2s ease',
    '&:hover': {
      transform: 'translateY(-3px)',
      borderColor: 'text.primary',
    },
  },
  projectTitle: {
    fontWeight: 700,
    fontSize: '1.05rem',
    mb: 1,
    color: 'text.primary',
  },
  description: {
    color: 'text.secondary',
    fontSize: '0.85rem',
    lineHeight: 1.6,
    mb: 1.5,
    '& p': { m: 0, mb: 1 },
    '& a': {
      color: 'text.primary',
      textDecoration: 'underline',
      textUnderlineOffset: '2px',
      '&:hover': { color: 'text.secondary' },
    },
  },
  stackContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 0.75,
    mb: 2,
  },
  stackChip: {
    backgroundColor: 'transparent',
    border: '1px solid',
    borderColor: 'divider',
    color: 'text.secondary',
    fontFamily: '"Sometype Mono", monospace',
    fontWeight: 500,
    borderRadius: 1,
    height: 24,
    fontSize: '0.72rem',
    textTransform: 'lowercase',
    '& .MuiChip-label': { px: 1 },
  },
  linksContainer: {
    mt: 'auto',
    flexWrap: 'wrap',
  },
  linkButton: {
    fontWeight: 600,
    fontSize: '0.8rem',
    color: 'text.primary',
    borderColor: 'text.primary',
    borderRadius: 1,
    textTransform: 'none',
    '&:hover': {
      backgroundColor: 'text.primary',
      color: 'background.default',
      borderColor: 'text.primary',
    },
  },
};
